---
title: "Comparing Balancing Techniques"
author: "Eric W. Bridgeford"
date: "2024-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(ggplot2)
require(tidyverse)
require(grid)
require(ggExtra)
require(causalBatch)
require(nnet)
require(MASS)
require(gridExtra)
```

```{r}
colors=c("0"="#d95f02", "1"="#7570b3")
make_covar_sims <- function(n=500, unbalancedness=1, K=2, coef=2) {
  # generate one-of-K class assignments
  if (K > 3) {
    stop("Not supported for K>3.")
  }
  class <- apply(rmultinom(n, size=1, prob=rep(1/K, K)) == 1, 2, which) - 1
  
  xs <- t(sapply(class, function(k) {
    if (k == 1) {
      x1 <- rbeta(1, shape1=coef, shape2=unbalancedness*coef)
      x2 <- rbeta(1, shape1=coef, shape2=unbalancedness*coef)
    } else if (k == 2) {
      x1 <- rbeta(1, shape1=coef*unbalancedness, shape2=coef)
      x2 <- rbeta(1, shape1=coef*unbalancedness, shape2=coef)
    } else {
      x1 <- rbeta(1, shape1=coef, shape2=coef)
      x2=rbeta(1, shape1=coef, shape2=coef)
    }
    return(c(x1, x2))
  }))
  
  return(data.frame(Class=factor(class, levels=as.character(0:(K-1))), "X1"=xs[,1], "X2"=xs[,2]))
}

wt_marginal_hist2d <- function(data, xtitle="", ytitle="", title="") {
  scatter.plt <- ggplot(data, aes(x=X1, y=X2, color=Class, group=Class, size=Weight)) +
    geom_point(alpha=0.7) +
    theme_bw() +
    scale_color_manual(values=colors) +
    labs(x=xtitle, y=ytitle, color="Exposure") +
    coord_cartesian(xlim=c(0, 1), ylim=c(0, 1), expand=FALSE) +
    guides(color=FALSE, size=FALSE)
  
  xmarg <- ggplot(data, aes(color=Class, group=Class, fill=Class)) +
    geom_density(aes(X1, y=..scaled../max(..scaled..), weight=Weight), alpha=0.5) +
    theme_bw() +
    theme(title=element_text(colour="#FFFFFF"), text=element_text(colour="#FFFFFF"),
          line = element_line(colour="#FFFFFF"), axis.ticks=element_line(colour="#FFFFFF"),
          panel.grid = element_blank(),
          axis.text=element_text(colour="#FFFFFF"),
          axis.ticks.x=element_blank(), axis.text.x=element_blank()) +
    scale_fill_manual(values=colors) +
    scale_color_manual(values=colors) +
    labs(x=xtitle) +
    scale_x_continuous(limits=c(0, 1), expand=c(0, 0)) +
    scale_y_continuous(expand=c(0, 0)) +
    guides(color=FALSE, fill=FALSE)
  
  ymarg <- ggplot(data, aes(color=Class, group=Class, fill=Class)) +
    geom_density(aes(X1, y=..scaled../max(..scaled..), weight=Weight), alpha=0.5) +
    theme_bw() +
    theme(title=element_text(colour="#FFFFFF"), text=element_text(colour="#FFFFFF"),
          line = element_line(colour="#FFFFFF"), axis.ticks=element_line(colour="#FFFFFF"),
          panel.grid = element_blank(),
          axis.text=element_text(colour="#FFFFFF"),
          axis.ticks.y=element_blank(), axis.text.y=element_blank()) +
    scale_fill_manual(values=colors) +
    scale_color_manual(values=colors) +
    labs(x=ytitle) +
    scale_x_continuous(limits=c(0, 1), expand=c(0, 0)) +
    scale_y_continuous(expand=c(0, 0)) +
    guides(color=FALSE, fill=FALSE,) +
    coord_flip()
  
  grid.arrange(xmarg, grid.rect(gp=gpar(col="white")), scatter.plt, ymarg, ncol=2,
              widths=c(0.8, 0.2), heights=c(0.3, 0.8))
}

marginal_hist2d <- function(data, xtitle="", ytitle="", title="") {
  scatter.plt <- ggplot(data, aes(x=X1, y=X2, color=Class, group=Class)) +
    geom_point(alpha=0.7) +
    scale_color_manual(values=colors) +
    theme_bw() +
    labs(x=xtitle, y=ytitle, color="Exposure") +
    coord_cartesian(xlim=c(0, 1), ylim=c(0, 1), expand=FALSE) +
    guides(color=FALSE)
  
  xmarg <- ggplot(data, aes(color=Class, group=Class, fill=Class)) +
    geom_density(aes(X1, y=..scaled../max(..scaled..)), alpha=0.5) +
    theme_bw() +
    scale_fill_manual(values=colors) +
    scale_color_manual(values=colors) +
    theme(title=element_text(colour="#FFFFFF"), text=element_text(colour="#FFFFFF"),
          line = element_line(colour="#FFFFFF"), axis.ticks=element_line(colour="#FFFFFF"),
          panel.grid = element_blank(),
          axis.text=element_text(colour="#FFFFFF"),
          axis.ticks.x=element_blank(), axis.text.x=element_blank()) +
    labs(x=xtitle) +
    scale_x_continuous(limits=c(0, 1), expand=c(0, 0)) +
    scale_y_continuous(expand=c(0, 0)) +
    guides(color=FALSE, fill=FALSE)
  
  ymarg <- ggplot(data, aes(color=Class, group=Class, fill=Class)) +
    geom_density(aes(X1, y=..scaled../max(..scaled..)), alpha=0.5) +
    theme_bw() +
    scale_fill_manual(values=colors) +
    scale_color_manual(values=colors) +
    theme(title=element_text(colour="#FFFFFF"), text=element_text(colour="#FFFFFF"),
          line = element_line(colour="#FFFFFF"), axis.ticks=element_line(colour="#FFFFFF"),
          panel.grid = element_blank(),
          axis.text=element_text(colour="#FFFFFF"),
          axis.ticks.y=element_blank(), axis.text.y=element_blank()) +
    labs(x=ytitle) +
    scale_x_continuous(limits=c(0, 1), expand=c(0, 0)) +
    scale_y_continuous(expand=c(0, 0)) +
    guides(color=FALSE, fill=FALSE,) +
    coord_flip()
  
  grid.arrange(xmarg, grid.rect(gp=gpar(col="white")), scatter.plt, ymarg, ncol=2,
               widths=c(0.8, 0.2), heights=c(0.3, 0.8))
}

calc_propensities <- function(data) {
  if (length(unique(data$Class)) > 2) {
    mod <- multinom("Class ~ X1 + X2", data=data)
    probs <- predict(mod, data, type="probs")
  } else {
    mod <- glm("Class ~ X1 + X2", data=data, family = binomial(link="logit"))
    probs <- predict(mod, data, type="response")
  }
  probs
}

prop_hist <- function(data, xtitle="Propensity", ytitle="", title="") {
  ggplot(data, aes(color=Class, group=Class, fill=Class)) +
    geom_histogram(aes(x=Propensity, y=..ncount../max(..ncount..)), bins=30, position="identity", alpha=0.5) +
    geom_jitter(aes(x=Propensity, y=ifelse(as.numeric(Class) == 1, -.1, 1.1)), height=.1, alpha=0.7) +
    scale_fill_manual(values=colors) +
    scale_color_manual(values=colors) +
    ylab(ytitle) +
    xlab(xtitle) +
    theme_bw() +
    theme(panel.grid=element_blank()) +
    guides(color=FALSE, fill=FALSE) +
    scale_y_continuous(limits=c(-.23, 1.23), breaks=c(0, .5, 1)) +
    scale_x_continuous(limits=c(0, 1))
}

wt_prop_hist <- function(data, xtitle="Propensity", ytitle="", title="") {
  ggplot(data, aes(color=Class, group=Class, fill=Class)) +
    geom_histogram(aes(x=Propensity, y=..ncount../max(..ncount..), weight=Weight), bins=30, position="identity", alpha=0.5) +
    geom_jitter(aes(x=Propensity, y=ifelse(as.numeric(Class) == 1, -.1, 1.1), size=Weight), height=.1, alpha=0.7) +
    scale_fill_manual(values=colors) +
    scale_color_manual(values=colors) +
    ylab(ytitle) +
    xlab(xtitle) +
    theme_bw() +
    theme(panel.grid=element_blank()) +
    guides(color=FALSE, fill=FALSE, size=FALSE) +
    scale_y_continuous(limits=c(-.23, 1.23), breaks=c(0, .5, 1)) +
    scale_x_continuous(limits=c(0, 1))
}

```

```{r}
covars <- make_covar_sims(n=500, unbalancedness=2, coef=3)
covars$Propensity <- calc_propensities(covars)

covar.marg.plt <- marginal_hist2d(covars, xtitle="Covariate 1",
                              ytitle = "Covariate 2")
covar.prop.plt <- prop_hist(covars, xtitle="Propensity",
                            ytitle="Normalized Count")

covar.plt <- arrangeGrob(covar.marg.plt, covar.prop.plt, ncol=1)
```

## Propensity Trimming

```{r}
retain.ids <- cb.align.vm_trim(covars$Class, covars %>% dplyr::select(X1, X2))
covars.prop_trim <- covars[retain.ids,]

covar.pt.marg.plt <- marginal_hist2d(covars.prop_trim, xtitle="Covariate 1",
                                     ytitle="Covariate 2")
covar.pt.prop.plt <- prop_hist(covars.prop_trim, xtitle="Propensity",
                            ytitle="Normalized Count")

pt.plt <- arrangeGrob(covar.pt.marg.plt, covar.pt.prop.plt, ncol=1)
```

## IPW

```{r}
get_weights <- function(data) {
  probs <- calc_propensities(data)
  if (is.null(dim(probs))) {
    return(1/ifelse(data$Class == 0, 1-probs, probs))
  } else {
    return(1/sapply(1:nrow(data), function(i) probs[i,as.numeric(data$Class[i])]))
  }
}
covars.ipw <- covars.prop_trim
covars.ipw$Weight <- get_weights(covars.ipw)

covar.ipw.marg.plt <- wt_marginal_hist2d(covars.ipw, xtitle="Covariate 1",
                                         ytitle="Covariate 2")
covar.ipw.prop.plt <- wt_prop_hist(covars.ipw, xtitle="Propensity",
                            ytitle="Normalized Count")

ipw.plt <- arrangeGrob(covar.ipw.marg.plt, covar.ipw.prop.plt, ncol=1)
```

## Matching

```{r}
retain.ids <- cb.align.kway_match(covars.prop_trim$Class, covars.prop_trim %>% dplyr::select(X1, X2),
                                  match.form = "X1 + X2",
                                  reference="1", match.args = list(method="nearest", distance="mahalanobis", 
                                                                   caliper=c(X1=.2, X2=.2)))$Retained.Ids

covars.match <- covars.prop_trim[retain.ids,]

covar.match.marg.plt <- marginal_hist2d(covars.match, xtitle="Covariate 1",
                                        ytitle="Covariate 2")
covar.match.prop.plt <- prop_hist(covars.match, xtitle="Propensity",
                            ytitle="Normalized Count")

match.plt <- arrangeGrob(covar.match.marg.plt, covar.match.prop.plt, ncol=1)
```

```{r, fig.height=4, fig.width=12}
grid.arrange(covar.plt, pt.plt, ipw.plt, match.plt, ncol=4)
```


