---
title: "Test Correlated Beta Sampling"
author: "Eric W. Bridgeford"
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
require(ggplot2)
require(causalBatch)
source("./utilities.R")
```

## Serial

```{r}
n <- 20000
corr = 0.5

corr.mtx <- matrix(corr, nrow=2)
diag(corr.mtx) <- 1

Xs <- generate_correlated_betas(n=n, alphas=c(4, 2), betas=c(2, 4), corr.mtx = corr.mtx)
```

```{r, fig.height=3, fig.width=5}
data.frame(X=c(Xs[,1], Xs[,2]), Dimension=factor(c(rep(1, n), rep(2, n)))) %>%
  ggplot(aes(x=(X+1)/2)) +
  geom_histogram(aes(y=after_stat(density), group=Dimension, fill=Dimension, color=Dimension),
                 position="identity", alpha=0.5, binwidth=0.02) +
  stat_function(fun=dbeta, args=list(4, 2), color="red") +
  stat_function(fun=dbeta, args=list(2, 4), color="blue") +
  theme_bw()
```

```{r}
print(sprintf("Correlation: %.3f", corr))
print(sprintf("Empirical Correlation: %.3f", cor(Xs[,1], Xs[,2])))
```

## Per group

```{r}
n <- 20000
pi <- 0.5

batches <- rbinom(n=n, size=1, prob=pi)
alpha <- 2; beta <- 4
Xs <- generate_correlated_betas_pergroup(batches, alpha, beta, beta, alpha, corr.mtx=1)
```

```{r, fig.height=3, fig.width=5}
ggplot(data.frame(X=(Xs+1)/2, Batch=factor(batches)), aes(x=X)) +
  geom_histogram(aes(y=after_stat(density), group=Batch, fill = Batch, color=Batch), position="identity", alpha=0.5, binwidth=0.02) +
  stat_function(fun=dbeta, args = list(alpha, beta), color="red") +
  stat_function(fun=dbeta, args = list(beta, alpha), color="blue") +
  theme_bw()
```


```{r}
rho <- 0.5
corr <- matrix(rho, nrow=3, ncol=3)
diag(corr) <- 1

batches <- rbinom(n=n, size=1, prob=pi)
Xs <- generate_correlated_betas_pergroup(batches, rep(alpha, 3), rep(beta, 3), rep(beta, 3), rep(alpha, 3), corr.mtx=corr)
print(cor(Xs[batches == 0,]))
print(cor(Xs[batches == 1,]))
```

```{r, fig.height=3, fig.width=5}
ggplot(data.frame(X=(Xs[,1]+1)/2, Batch=factor(batches)), aes(x=X)) +
  geom_histogram(aes(y=after_stat(density), group=Batch, fill = Batch, color=Batch), position="identity", alpha=0.5, binwidth=0.02) +
  stat_function(fun=dbeta, args = list(alpha, beta), color="red") +
  stat_function(fun=dbeta, args = list(beta, alpha), color="blue") +
  theme_bw()
```



```{r, fig.height=3, fig.width=5}
ggplot(data.frame(X=(Xs[,2]+1)/2, Batch=factor(batches)), aes(x=X)) +
  geom_histogram(aes(y=after_stat(density), group=Batch, fill = Batch, color=Batch), position="identity", alpha=0.5, binwidth=0.02) +
  stat_function(fun=dbeta, args = list(alpha, beta), color="red") +
  stat_function(fun=dbeta, args = list(beta, alpha), color="blue") +
  theme_bw()
```



```{r, fig.height=3, fig.width=5}
ggplot(data.frame(X=(Xs[,3]+1)/2, Batch=factor(batches)), aes(x=X)) +
  geom_histogram(aes(y=after_stat(density), group=Batch, fill = Batch, color=Batch), position="identity", alpha=0.5, binwidth=0.02) +
  stat_function(fun=dbeta, args = list(alpha, beta), color="red") +
  stat_function(fun=dbeta, args = list(beta, alpha), color="blue") +
  theme_bw()
```
