---
title: "Collider Simulations"
author: "Eric W. Bridgeford"
date: "2024-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
require(ggplot2)
require(grid)
require(gridExtra)
source("./collision_methods.R")
source("./collider_sims.R")
source("./utilities.R")
```

# Log-Odds Scale

```{r}
lo.methods <- list("oracle"=oracle.collision.lo, "conditional"=conditional.collision.lo, 
                "filtered"=filtering.collision.lo, "matching"=causal.matching.lo,
                "ipw"=causal.ipw.lo)
simulations <- list("Linear"=collider.sim_linear, "Non-Linear"=collider.sim_nonlinear, "Non-Monotone"=collider.sim_nonmonotone)
batch.cols <- c("0"="#d95f02", "1"="#7570b3")
lo.method.cols <- c("conditional"="#916e99", "filtered"="#916e99", "oracle"="#DD0000", 
                 "matching"="#22bc22", "ipw"="#22bc22")

lo.method.lines <- c("oracle"="solid", "conditional"="solid", "filtered"="dashed", 
                 "matching"="solid", "ipw"="dashed")
```

```{r}
R = 500
ns <- floor(2^seq(7, 11, length.out=8))

sim_results <- do.call(rbind, lapply(names(simulations), function(simn) {
  do.call(rbind, lapply(ns, function(n) {
    print(sprintf("Simulation: %s, SS: %d", simn, n))
    do.call(rbind, mclapply(1:R, function(i) {
      sim = do.call(simulations[[simn]], list(n=n, confounding=0.2))
      do.call(rbind, lapply(names(lo.methods), function(methn) {
        tryCatch({
          est <- suppressWarnings(do.call(lo.methods[[methn]], list(sim$Ys, sim$Ts, sim$Xs, usable=sim$usable,
                                                Ttrue=sim$Ttrue, xfm=linear.xfm))$est)
          return(data.frame(Context=simn, Method=methn, n=n, Idx=i, Estimate=est))
        }, error=function(e) {
          return(data.frame(Context=simn, Method=methn, n=n, Idx=i, Estimate=NaN))
        })
      }))
    }, mc.cores=parallel::detectCores() - 2))
  }))
}))
saveRDS(sim_results, file="../data/simulations/collider_sims.rds")
```

```{r, fig.height=2, fig.width=8}
sim_results <- readRDS("../data/simulations/collider_sims.rds")

sim_results <- sim_results %>%
  mutate(Truth=1) %>%
  mutate(Error=abs(Estimate - Truth)/Truth)

processed <- sim_results %>%
  group_by(Context, Method, n) %>%
  summarize(Estimate.Mean=mean(Estimate), Error.Mean=mean(Error), Estimate.SE=sd(Estimate)/sqrt(n()), Error.SE=sd(Error)/sqrt(n())) %>%
  pivot_longer(
      cols = c(Estimate.Mean, Error.Mean, Estimate.SE, Error.SE),
      names_to = c("Name", "Measure"),
      names_sep = "\\.",
      values_to = "Value"
  ) %>%
  pivot_wider(
      names_from = Measure,
      values_from = Value
  )

lo.plot <- processed %>%
  mutate(Method=factor(Method)) %>%
  filter(Name == "Error") %>%
  mutate() %>%
  ggplot(aes(x=n, y=Mean, group=Method, color=Method, linetype=Method)) +
  geom_line() +
  #geom_errorbar(aes(ymin=Mean - SE, ymax=Mean + SE)) +
  theme_bw() +
  geom_line(linewidth=1.05) +
  scale_color_manual(values=lo.method.cols) +
  scale_x_continuous(name="Number of Samples", trans="log2") +
  scale_linetype_manual(values=lo.method.lines) +
  facet_grid(Name ~ Context, scales="free_y") +
  theme_bw() +
  coord_cartesian(ylim=c(0, 1), expand=FALSE) +
  theme(panel.grid=element_blank(), strip.background=element_blank())
```
# Mean Difference Scale

```{r}
md.methods <- list("oracle"=oracle.collision.md, "naive oracle"=oracle.naive.collision.md, "conditional"=conditional.collision.md, 
                "filtered"=filtering.collision.md, "drtmle"=nebel.collision.md)

simulations <- list("Linear"=collider.sim_linear, "Non-Linear"=collider.sim_nonlinear, "Non-Monotone"=collider.sim_nonmonotone)
batch.cols <- c("0"="#d95f02", "1"="#7570b3")
md.method.cols <- c("conditional"="#916e99", "filtered"="#916e99", "oracle"="#DD0000", "naive oracle"="#DD0000",
                 "drtmle"="#bf9000")

md.method.lines <- c("oracle"="dashed", "naive oracle"="solid", "conditional"="solid", "filtered"="dashed", 
                 "drtmle"="solid")
```

```{r}
R = 200
ns <- floor(2^seq(7, 11, length.out=8))
ntrue <- 100000

sim_results <- do.call(rbind, lapply(names(simulations), function(simn) {
  do.call(rbind, lapply(ns, function(n) {
    print(sprintf("Simulation: %s, SS: %d", simn, n))
    sim_true <- do.call(simulations[[simn]], list(n=ntrue, confounding=0.2))
    phi.star <- mean(sim_true$Ttrue[sim_true$Ys == 1]) - mean(sim_true$Ttrue[sim_true$Ys == 0])
    do.call(rbind, mclapply(1:R, function(i) {
      sim <- do.call(simulations[[simn]], list(n=n, confounding=0.2))
      do.call(rbind, lapply(names(methods), function(methn) {
        tryCatch({
          est <- suppressWarnings(do.call(methods[[methn]], list(sim$Ys, sim$Ts, sim$Xs, usable=sim$usable,
                                                Ttrue=sim$Ttrue, xfm=linear.xfm))$est)
          return(data.frame(Context=simn, Method=methn, n=n, Idx=i, Estimate=est, Truth=phi.star))
        }, error=function(e) {
          return(data.frame(Context=simn, Method=methn, n=n, Idx=i, Estimate=NaN, Truth=phi.star))
        })
      }))
    }, mc.cores=parallel::detectCores() - 4))
  }))
}))
saveRDS(sim_results, file="../data/simulations/collider_sims_md.rds")
```


```{r, fig.height=2, fig.width=8}
sim_results <- readRDS("../data/simulations/collider_sims_md.rds")

sim_results <- sim_results %>%
  mutate(Error=abs(Estimate - Truth)/Truth)

processed <- sim_results %>%
  group_by(Context, Method, n) %>%
  summarize(Estimate.Mean=mean(Estimate), Error.Mean=mean(Error), Estimate.SE=sd(Estimate)/sqrt(n()), Error.SE=sd(Error)/sqrt(n())) %>%
  pivot_longer(
      cols = c(Estimate.Mean, Error.Mean, Estimate.SE, Error.SE),
      names_to = c("Name", "Measure"),
      names_sep = "\\.",
      values_to = "Value"
  ) %>%
  pivot_wider(
      names_from = Measure,
      values_from = Value
  )

md.plot <- processed %>%
  mutate(Method=factor(Method)) %>%
  filter(Name == "Error", Method != "oracle") %>%
  ggplot(aes(x=n, y=Mean, group=Method, color=Method, linetype=Method)) +
  geom_line() +
  #geom_errorbar(aes(ymin=Mean - SE, ymax=Mean + SE)) +
  theme_bw() +
  geom_line(linewidth=1.05) +
  scale_color_manual(values=md.method.cols) +
  scale_x_continuous(name="Number of Samples", trans="log2") +
  scale_linetype_manual(values=md.method.lines) +
  coord_cartesian(ylim=c(0, 1), expand=FALSE) +
  facet_grid(Name ~ Context, scales="free_y") +
  theme_bw() +
  theme(panel.grid=element_blank(), strip.background=element_blank())
```

```{r, fig.width=8, fig.height=4}
plt.collision <- grid.arrange(lo.plot, md.plot, nrow=2)
ggsave("../Figure_dump/sims_collider_draft.pdf", plt.collision, width=10, height=4)
```

# Statistical Power Investigations

```{r}
pow.methods <- list("oracle"=oracle.collision.lo, "conditional, lo"=conditional.collision.lo, 
                "filtered, lo"=filtering.collision.lo, "conditional, md"=conditional.collision.md,
                "filtered, md"=filtering.collision.md, "drtmle"=nebel.collision.md,
                "matching"=causal.matching.lo, "ipw"=causal.ipw.lo)

md.method.cols <- c("conditional, lo"="#916e99", "filtered, lo"="#916e99",
                    "oracle"="#DD0000", "conditional, md"="#916e99", "filtered, md"="#916e99",
                    "drtmle"="#bf9000", "matching"="#22bc22", "ipw"="#22bc22")

md.method.lines <- c("oracle"="solid", "conditional, lo"="solid", "filtered, lo"="dashed", 
                    "drtmle"="solid", "conditional, md"="", "filtered, md"="",
                    "matching"="solid", "ipw"="dashed")
n.sens_spec <- 512
```

### Sensitivity as a function of effect size

```{r}
R = 200
eff_szs <- 2^(seq(-1, log2(2.5), length.out=9)) - 0.5

sim_results <- do.call(rbind, lapply(names(simulations), function(simn) {
  do.call(rbind, lapply(eff_szs, function(eff_sz) {
    print(sprintf("Simulation: %s, Eff sz: %.3f", simn, eff_sz))
    do.call(rbind, mclapply(1:R, function(i) {
      print(i)
      sim <- do.call(simulations[[simn]], list(n=n.sens_spec, eff_sz=eff_sz, confounding=0.2))
      do.call(rbind, lapply(names(pow.methods), function(methn) {
        tryCatch({
          res <- suppressWarnings(do.call(pow.methods[[methn]], list(sim$Ys, sim$Ts, sim$Xs, usable=sim$usable,
                                                Ttrue=sim$Ttrue, xfm=linear.xfm)))
          return(data.frame(Context=simn, Method=methn, Truth=eff_sz, Idx=i, estimate=res$est, pvalue=res$pvalue))
        }, error=function(e) {
          return(data.frame(Context=simn, Method=methn, Truth=eff_sz, Idx=i, estimate=NaN, pvalue=NaN))
        })
      }))
    }, mc.cores=parallel::detectCores() - 2))
  }))
}))
saveRDS(sim_results, file="../data/simulations/collider_sims_sens.rds")
```

```{r}
alpha = .05
sim_results <- readRDS("../data/simulations/collider_sims_sens.rds")

sim_results <- sim_results %>%
  mutate(Outcome = pvalue < alpha)

processed <- sim_results %>%
  group_by(Context, Method, Truth) %>%
  summarize(Power=mean(Outcome))

sens.plot <- processed %>%
  mutate(Method=factor(Method)) %>%
  filter(!(Method %in% c("conditional, md", "filtered, md"))) %>%
  ggplot(aes(x=Truth, y=Power, group=Method, color=Method, linetype=Method)) +
  geom_line() +
  #geom_errorbar(aes(ymin=Mean - SE, ymax=Mean + SE)) +
  theme_bw() +
  geom_line(linewidth=1.05) +
  scale_color_manual(values=md.method.cols) +
  scale_x_continuous(name="Effect Size") +
  scale_linetype_manual(values=md.method.lines) +
  coord_cartesian(ylim=c(0, 1), expand=FALSE) +
  facet_grid(. ~ Context, scales="free_y") +
  theme_bw() +
  theme(panel.grid=element_blank(), strip.background=element_blank())
```

### Specificity as a function of level of confounding

```{r}
confounds.sz <- seq(0, 0.6, length.out=7)

sim_results <- do.call(rbind, lapply(names(simulations), function(simn) {
  do.call(rbind, lapply(confounds.sz, function(confound.sz) {
    print(sprintf("Simulation: %s, Confound: %.3f", simn, confound.sz))
    do.call(rbind, mclapply(1:R, function(i) {
      sim <- do.call(simulations[[simn]], list(n=n.sens_spec, eff_sz=0, confounding=confound.sz))
      do.call(rbind, lapply(names(pow.methods), function(methn) {
        tryCatch({
          res <- suppressWarnings(do.call(pow.methods[[methn]], list(sim$Ys, sim$Ts, sim$Xs, usable=sim$usable,
                                                Ttrue=sim$Ttrue, xfm=linear.xfm)))
          return(data.frame(Context=simn, Method=methn, Confounding=confound.sz, Idx=i, estimate=res$est, pvalue=res$pvalue))
        }, error=function(e) {
          return(data.frame(Context=simn, Method=methn, Confounding=confound.sz, Idx=i, estimate=NaN, pvalue=NaN))
        })
      }))
    }, mc.cores=parallel::detectCores() - 4))
  }))
}))
saveRDS(sim_results, file="../data/simulations/collider_sims_spec.rds")
```