---
title: "Comparison Batch Effect Correction"
author: "Eric W. Bridgeford"
date: "2024-02-13"
output: html_document
---

```{r setup, include=FALSE}
require(ggplot2)
require(tidyverse)
require(gridExtra)
require(ggpubr)
source('./simulations.R')
source('./combat_seq_return.R')
```

```{r}
methods <- list("Pois"=ass.pois, "cPois"=cond.pois, "oPois"=oracle.pois, "sPois"=strat.pois,
                "ipwPois"=ipw.pois, "mPois"=match.pois)
simulations <- list("Linear"=sim_linear, "Non-Linear"=sim_sigmoid, "Non-Monotone"=sim_impulse)
batch.cols <- c("0"="#d95f02", "1"="#7570b3")
method.cols <- c("Pois"="#916e99", "cPois"="#916e99", "oPois"="#916e99", 
                 "sPois"="#658cbb", 
                 "ipwPois"="#22bc22", "mPois"="#22bc22")

method.lines <- c("Pois"=3, "cPois"=2, "oPois"=1, 
                 "sPois"=1, 
                 "ipwPois"=2, "mPois"=1)
```

# Illustrative Rows

```{r}
sims <- lapply(simulations, function(sim) {
  do.call(sim, list(n=200, d=1, unbalancedness=2))
})

sim.raw <- do.call(rbind, lapply(names(sims), function(simname) {
  sim=sims[[simname]]
  return(data.frame(Y=sim$Ys[,1], Batch=sim$Ts, X=sim$Xs, Context=simname) %>%
    dplyr::mutate(logY=log(Y)))
}))

sim.true <- do.call(rbind, lapply(names(sims), function(simname) {
  sim=sims[[simname]]
  return(data.frame(Y=sim$Ytrue[,1], Batch=sim$Ttrue, X=sim$Xtrue, Context=simname) %>%
    dplyr::mutate(logY=log(Y)))
}))

sim.cate <- sim.true %>%
  pivot_wider(names_from="Batch", id_cols=c("X", "Context"), values_from=c("Y", "logY")) %>%
  group_by(X, Context) %>%
  mutate(CATE.u=max(Y_0, Y_1), CATE.l = min(Y_0, Y_1),
         sys_CATE.u=max(logY_0, logY_1), sys_CATE.l=min(logY_0, logY_1))

row1 <- ggplot() +
  geom_ribbon(data=sim.cate, aes(x=X, ymin=CATE.l, ymax=CATE.u), fill="red", alpha=0.3) +
  geom_point(data=sim.raw, aes(x=X, y=Y, color=Batch, group=Batch), alpha=0.5) +
  geom_line(data=sim.true, aes(x=X, y=Y, color=Batch, group=Batch), linewidth=1.2) +
  facet_grid(.~Context) +
  scale_color_manual(values=batch.cols) +
  theme_bw() +
  scale_x_continuous(name="Covariate", breaks=c(-1, 0, 1), expand=c(0, 0)) +
  scale_y_continuous(name="Number of Fibers", expand=c(0, 0)) +
  theme(panel.grid=element_blank(), strip.background=element_blank())

row2 <- ggplot() +
  geom_ribbon(data=sim.cate, aes(x=X, ymin=sys_CATE.l, ymax=sys_CATE.u), fill="red", alpha=0.3) +
  geom_point(data=sim.raw, aes(x=X, y=logY, color=Batch, group=Batch), alpha=0.5) +
  geom_line(data=sim.true, aes(x=X, y=logY, color=Batch, group=Batch), linewidth=1.2) +
  facet_grid(.~Context) +
  scale_color_manual(values=batch.cols) +
  theme_bw() +
  scale_x_continuous(name="Covariate", breaks=c(-1, 0, 1), expand=c(0, 0)) +
  scale_y_continuous(name="log(Number of Fibers)", expand=c(0, 0)) +
  theme(panel.grid=element_blank(), strip.background=element_blank())
```

```{r}
eff_szs <- c("Effect"=1, "No Effect"=0)
unbalancednesses <- seq(1, 4, length.out=8)
d = 1; n=200; R = 1000
oracle_xfms <- list("Linear"=linear.xfm, "Non-Linear"=sigmoid.xfm, "Non-Monotone"=impulse.xfm)

sim_results <- do.call(rbind, lapply(names(simulations), function(simn) {
  sim_fn <- simulations[[simn]]
  do.call(rbind, lapply(names(eff_szs), function(eff_szn) {
    eff_sz <- eff_szs[[eff_szn]]
    print(sprintf("Context: %s, Effect Size: %.3f", simn, eff_sz))
    do.call(rbind, lapply(unbalancednesses, function(unbalancedness) {
      do.call(rbind, mclapply(1:R, function(r) {
        if (r %% 100 == 0) {
          print(sprintf("Finished %d out of %d...", r, R))
        }
        sim <- do.call(sim_fn, list(unbalancedness=unbalancedness, n=n, d=d, eff_sz=eff_sz))
        do.call(rbind, lapply(names(methods), function(methn) {
          tryCatch({
            mod <- suppressWarnings(do.call(methods[[methn]], list(sim$Ys, sim$Ts, sim$Xs, xfm=oracle_xfms[[simn]], nstrata=5)))
            return(data.frame(Context=simn, `Effect Size`=eff_sz, Overlap=sim$Overlap, Method=methn, i=r,
                              Error=abs(eff_sz - mod$fit[[1]]$coefficients["Batch1"])))
            }, error=function(e) {
              return(data.frame(Context=simn, `Effect Size`=eff_sz, Overlap=sim$Overlap, Method=methn, i=r, Error=NaN))
          })
        }))
      }, mc.cores = parallel::detectCores() - 1))
    }))
  }))
}))
saveRDS(sim_results, file="../data/simulations/est_sims_nounmeas.rds")
```

```{r}
sim_results <- readRDS("../data/simulations/est_sims_nounmeas.rds")

sim_sum <- sim_results %>%
  group_by(Context, Effect.Size, Overlap, Method) %>%
  summarize(Nfail = sum(is.nan(Error)), Error=mean(Error, na.rm=TRUE))

row.34 <- sim_sum %>%
  mutate(Method=factor(Method, levels=c("Pois", "cPois", "oPois", "sPois", "ipwPois", "mPois"), ordered=TRUE)) %>%
  ggplot(aes(x=Overlap, y=Error, color=Method, group=Method, linetype=Method)) +
  geom_line(linewidth=1.05) +
  scale_color_manual(values=method.cols) +
  scale_linetype_manual(values=method.lines) +
  scale_y_continuous(name="Estimation Error", expand=c(0, 0)) +
  scale_x_continuous(trans=compose_trans("log10", "reverse"), expand=c(0, 0)) +
  coord_cartesian(ylim=c(0, 2), xlim=c(1, .035)) +
  facet_grid(Effect.Size ~ Context) +
  theme_bw() +
  theme(panel.grid=element_blank(), strip.background=element_blank())
```

```{r}
grid.arrange(row1, row2, row.34, heights=c(1, 1, 2), nrow=3)
```


