---
title: "Test Correlated Beta Sampling"
author: "Eric W. Bridgeford"
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
require(ggplot2)
require(causalBatch)
source('./simulations.R')
```

```{r}
n <- 20000
pi <- 0.5


batches <- rbinom(n=n, size=1, prob=pi)
alpha <- 2; beta <- 4
Xs <- generate_correlated_betas(batches, rep(alpha, 1), rep(beta, 1), rep(beta, 1), rep(alpha, 1), corr.mtx=1)
```

```{r, fig.height=3, fig.width=5}
ggplot(data.frame(X=Xs, Batch=factor(batches)), aes(x=X)) +
  geom_histogram(aes(y=after_stat(density), group=Batch, fill = Batch, color=Batch), position="identity", alpha=0.5, binwidth=0.02) +
  stat_function(fun=dbeta, args = list(alpha, beta), color="red") +
  stat_function(fun=dbeta, args = list(beta, alpha), color="blue") +
  theme_bw()
```


```{r}
rho <- 0.5
corr <- matrix(rho, nrow=3, ncol=3)
diag(corr) <- 1

generate_correlated_betas <- function(batches, alphas1, betas1, alphas2, betas2, corr.mtx=NULL) {
  n = length(batches)
  ndim <- ifelse(is.null(dim(corr.mtx)), 1, nrow(corr.mtx))
  if (ndim > 1) {
    # Create a Gaussian copula with the specified correlation
    copula_obj <- normalCopula(param=P2p(corr.mtx), dim = ndim, dispstr="un")
    
    # Generate uniform samples from the copula
    u <- rCopula(n, copula_obj)
  } else {
    u <- matrix(runif(n), ncol=1)
  }
  
  # Transform uniform samples to beta-distributed variables
  Xs <- do.call(cbind, lapply(1:ndim, function(k) {
    sapply(1:length(batches), function(i) {
      ifelse(batches[i] == 0, qbeta(u[i,k], alphas1[k], betas1[k]), 
             qbeta(u[i,k], alphas2[k], betas2[k]))
    })
  }))
  return(matrix(Xs, ncol=ndim))
}

batches <- rbinom(n=n, size=1, prob=pi)
Xs <- generate_correlated_betas(batches, rep(alpha, 3), rep(beta, 3), rep(beta, 3), rep(alpha, 3), corr.mtx=corr)
print(cor(Xs[batches == 0,]))
print(cor(Xs[batches == 1,]))
```

```{r, fig.height=3, fig.width=5}
ggplot(data.frame(X=Xs[,1], Batch=factor(batches)), aes(x=X)) +
  geom_histogram(aes(y=after_stat(density), group=Batch, fill = Batch, color=Batch), position="identity", alpha=0.5, binwidth=0.02) +
  stat_function(fun=dbeta, args = list(alpha, beta), color="red") +
  stat_function(fun=dbeta, args = list(beta, alpha), color="blue") +
  theme_bw()
```



```{r, fig.height=3, fig.width=5}
ggplot(data.frame(X=Xs[,2], Batch=factor(batches)), aes(x=X)) +
  geom_histogram(aes(y=after_stat(density), group=Batch, fill = Batch, color=Batch), position="identity", alpha=0.5, binwidth=0.02) +
  stat_function(fun=dbeta, args = list(alpha, beta), color="red") +
  stat_function(fun=dbeta, args = list(beta, alpha), color="blue") +
  theme_bw()
```



```{r, fig.height=3, fig.width=5}
ggplot(data.frame(X=Xs[,3], Batch=factor(batches)), aes(x=X)) +
  geom_histogram(aes(y=after_stat(density), group=Batch, fill = Batch, color=Batch), position="identity", alpha=0.5, binwidth=0.02) +
  stat_function(fun=dbeta, args = list(alpha, beta), color="red") +
  stat_function(fun=dbeta, args = list(beta, alpha), color="blue") +
  theme_bw()
```
